### ISSUE TITLE
Certain programs can't access files that are on an encrypted partition on Windows (ex: Google Drive for Desktop)

### ISSUE THREAD

**Issue by Totalus** [veracrypt/VeraCrypt#764]
I recently ran into two issues with third party programs that are unable not work properly if the path they need to access is on a VeraCrypt encrypted partition. I think the source of the issue might be the same and have something realted with Windows file access API, which might therefore affect other programs as well.

**[Google Drive for Desktop](https://www.google.com/intl/en_us/drive/download/)**
The first program is *Google Drive for Desktop* which allows to "sync" your Google Drive on a local computer without actually having to download all the content of your drive. It creates a virtual drive (just like VeraCrypt does) where you can see your online documents and has a cache folder that contains data for documents that you want to access offline or that are currently opened. I've noticed that when the cache folder is set to a directory inside a VeraCrypt partition, I am unable to open any documents from the virtual drive created by Google Filstream. I don't have any error log for this one unfortunately.

**CaPnP**
CaPnP is an data encoding system similar to Protobuf. But that's not really important. What is important is that when I tried to use it, I realized that I was getting a file access issue when I was trying to open a file if the file is on an encrypted partition, and fortunately here, I do have more details on the source of the error.

When I try to load a file (see steps to reproduce below), I get the following exception.

```py
Traceback (most recent call last):
  File "messageEncodingTest.py", line 5, in <module>
    my_capnp = capnp.load('test.capnp')
  File "capnp\lib\capnp.pyx", line 4030, in capnp.lib.capnp.load
  File "capnp\lib\capnp.pyx", line 3293, in capnp.lib.capnp.SchemaParser.load
capnp.lib.capnp.KjException: kj\filesystem-disk-win32.c++:376: failed: GetFileInformationByHandleEx(FileCompressionInfo): #87 Incorrect Parameter
stack: 7ffc73a63abd 7ffc73a63961 7ffc7395afb6 7ffc7395a32f 7ffc7395ed85 7ffc7395ecc4 7ffc7395aee9 7ffc7395adab 7ffc73aae68c 7ffc73aaa089 7ffc73aad990 7ffc73c36eb0 7ffc73a760ce 7ffc73a99a74 7ffc73a99da0 7ffc73c529b0 7ffc73c53276 7ffc73c53d41 7ffc73c3add5 7ffc73c3060e 7ffc73c3056c 7ffc73c30516 7ffc73dc7c84 7ffc73dc84ab 7ffc73dc7b52 7ffc73d14466 7ffc73d1450e 7ffc73caa3a7 7ffc73c21076 7ffc73c21051 7ff79e161257 7ffcece27033
```

So the issue seems to be realted to a Windows specific function ([`GetFileInformationByHandleEx`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyhandleex)), called [here](https://github.com/capnproto/capnproto/blob/b5ab41ea033874cb3c144b9ad87e3442a297ed55/c%2B%2B/src/kj/filesystem-disk-win32.c%2B%2B#L367), that is used to get some info about the file. But for some reason the call fails with error `#87 Incorrect Parameter` when the file is on a VeraCrypt partition.

**So where is the issue ?**

Well I don't know. I'm not sure why and how that fails and I don't know VeraCrypt under the hood enough to dig much deaper. I mainly wanted to share the details I was able to uncover, which might help someone more knowledgable to find the issue.

## Expected behavior
I expect the programs to work properly as they do when they are accessing the standard (non-encrypted) file system.

## Steps to reproduce
If you want to reproduce with CaPnP:

1. Create an empty file named `test.capnp`
2. Install capnp python package with `pip install pycapnp`
3. Run the following python script

```py
# Python 3
import capnp
capnp.remove_import_hook()
my_capnp = capnp.load('test.capnp') # This line should fail
```

## Your Environment

**VeraCrypt version:** 1.24-Update7

**Operating system and version:** Windows 10 build 19042.867

**System type:** 64-bit

**Comment by idrassi** [comment]
Thanks for the detailed report. I reviewed this again.

For the Cap'n Proto / pycapnp part, the failing API is `GetFileInformationByHandleEx(..., FileCompressionInfo, ...)`. This is a filesystem file-metadata query, not a VeraCrypt block I/O operation. VeraCrypt exposes a mounted volume as a disk device; the Windows filesystem driver mounted on top of it handles per-file metadata queries.

This exact Cap'n Proto failure was later reported upstream in capnproto/capnproto#2176 against VeraCrypt 1.26.15. Cap'n Proto fixed it by treating `ERROR_INVALID_PARAMETER` as “compression information unavailable” instead of making it fatal. The fix was merged in capnproto/capnproto#2178 and #2179 and is present in Cap'n Proto 1.1.0 and later.

For the Google Drive for desktop part, there isn't enough information here to conclude it has the same cause. Google current documentation says the Drive for desktop content cache is supported on NTFS on Windows. If the VeraCrypt volume used for the cache was FAT/exFAT, or if it was mounted as removable media, this may be outside Google Drive supported cache configuration.

At this stage I don't see evidence of a VeraCrypt data-access bug requiring a driver change. Recommended actions:
- update Cap'n Proto / pycapnp to a version containing the upstream fix
- use an NTFS-formatted VeraCrypt volume mounted as fixed media for Google Drive’s cache
- if this is still reproducible with current VeraCrypt, current Windows, and an NTFS fixed VeraCrypt volume, please provide the VeraCrypt version, Windows build, filesystem type, whether "mount as removable" is enabled, Google Drive logs, and a minimal `GetFileInformationByHandleEx(FileCompressionInfo)` test result.

Closing this for now. We can reopen if there is a current minimal reproduction pointing to VeraCrypt.
